

spring:
 
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    username: retire
    password: retire
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
    
    redis:
   
    database: 0
   
    host: 127.0.0.1
  
    port: 6379
    
   
    jedis:
      pool:
        
        max-idle: 8
       
        min-idle: 0
      
        max-active: 8
      
        max-wait: 0
   
    timeout: 500
    devtools: 
    restart: 
      enabled: true
      trigger-file: devtools.tg
      
pagehelper:
 helperDialect: oracle
 reasonable: true
 supportMethodsArguments: true
 params: count=countSql      

